{% set version = "dev" %}

package:
  name: jaws
  version: {{ version }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy >=1.11
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - scipy
    - requests
  run:
    - python
    - pandas
    - numpy >=1.11
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - scipy
    - requests

about:
  home: https://github.com/jaws/jaws
  license: Apache License, Version 2.0
  license_file: LICENSE
