{% set version = "dev" %}

package:
  name: jaws
  version: {{ version }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - scipy
    - requests
    - metpy
  run:
    - python
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - scipy
    - requests
    - metpy

about:
  home: https://github.com/jaws/jaws
  license: Apache-2.0
  license_file: LICENSE
